name       : etcher
version    : 1.2.0
release    : 2
source     :
    - git|https://github.com/resin-io/etcher.git : v1.2.0
license    : Apache-2.0
component  : system.util
summary    : Flash OS images to SD cards & USB drives, safely and easily
description: |
    Etcher is a powerful OS image flasher built with web technologies to ensure flashing an SDCard or USB drive is a pleasant and safe experience. It protects you from accidentally writing to your hard-drives, ensures every byte of data was written correctly and much more.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - jq
    - nodejs
setup      : |
    # Upstream doesn't support npm5 yet
    export PATH=$workdir/node_modules/.bin:$PATH
    npm install npm@4

    npm config set unsafe-perm=true
    %make electron-develop
build      : |
    %make package-electron DISABLE_UPDATES=1 RELEASE_TYPE=production
install    : |
    install -Dm00644 $workdir/assets/icon.png $installdir/usr/share/pixmaps/etcher.png
    install -Dm00644 $pkgfiles/etcher.desktop $installdir/usr/share/applications/etcher.desktop

    install -dm00755 $installdir/usr/share/etcher/
    cp -R $workdir/dist/linux-unpacked/* $installdir/usr/share/etcher/

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/etcher/etcher-electron $installdir/usr/bin/etcher
