name       : etcher
version    : 1.1.2
release    : 1
source     :
    - https://github.com/resin-io/etcher/archive/v1.1.2.tar.gz : 5ba57fd6dd68a7a33c7409b4782c31a0925d25fff25c93fffacf6c009e19641b
license    : Apache-2.0
component  : system.util
networking : yes
summary    : Flash OS images to SD cards & USB drives, safely and easily
description: |
    Etcher is a powerful OS image flasher built with web technologies to ensure flashing an SDCard or USB drive is a pleasant and safe experience. It protects you from accidentally writing to your hard-drives, ensures every byte of data was written correctly and much more.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(xcursor)
    - pkgconfig(xcomposite)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - jq
    - nodejs
setup      : |
    npm config set unsafe-perm=true
    %make electron-develop
build      : |
    %make package-electron DISABLE_UPDATES=1
install    : |
    install -Dm644 $workdir/assets/icon.png $installdir/usr/share/pixmaps/etcher.png
    install -Dm644 $pkgfiles/etcher.desktop $installdir/usr/share/applications/etcher.desktop

    install -dm755 $installdir/usr/share/etcher/
    cp -R $workdir/dist/linux-unpacked/* $installdir/usr/share/etcher/

    install -dm755 $installdir/usr/bin
    ln -sv /usr/share/etcher/etcher-electron $installdir/usr/bin/etcher
